---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere_01.html 
keywords:  
summary:  
---
= 部署SnapCenter VMware vSphere的VMware vCenter外掛程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要在SnapCenter 虛擬化機器上使用支援VMware vSphere的功能來保護VM、資料存放區和應用程式一致的資料庫、您必須部署SnapCenter 適用於VMware vSphere的VMware外掛程式。

. 若為VMware vCenter 7.0.3及更新版本、請依照中的步驟進行 link:scpivs44_download_the_ova_open_virtual_appliance.html["下載開放式虛擬應用裝置（OVA）"^] 可將證書導入vCenter。
. 在瀏覽器中、瀏覽至VMware vSphere vCenter。
+

NOTE: 對於IPv6 HTML Web用戶端、您必須使用Chrome或Firefox。

. 登入* VMware vCenter單一登入頁面*。
. 在導覽窗格中、以滑鼠右鍵按一下任何虛擬機器的有效父物件（例如資料中心、資料夾、叢集或主機）、然後選取*部署OVF範本*以啟動VMware部署精靈。
. 在「*選取OVF範本*」頁面上、指定「.ova」檔案的位置（如下表所列）、然後按「*下一步*」。
+
|===
| 在此精靈頁面上… | 執行此操作… 


| 選取名稱和資料夾 | 輸入VM或vApp的唯一名稱、然後選取部署位置。 


| 選取資源 | 選取您要執行已部署VM範本的資源。 


| 檢閱詳細資料 | 驗證「.ova」範本詳細資料。 


| 授權合約 | 選取「*我接受所有授權合約*」核取方塊。 


| 選擇儲存設備 | 定義儲存已部署OVF範本檔案的位置和方式。 


| 選取「網路」 | 選取來源網路並將其對應至目的地網路。 


| 自訂範本  a| 
在*登錄至現有vCenter *中、輸入vCenter認證資料。在*「Create SnapCenter VMware vSphere Plug-In for VMware vSphere」認證*中、輸入SnapCenter VMware vSphere認證的「VMware Plug-in」。


NOTE: 記下您指定的使用者名稱和密碼。如果SnapCenter 您想稍後修改VMware vSphere的VMware vSphere組態、則需要使用這些認證。

在*設定網路內容*中、輸入網路資訊。在*設定日期與時間*中、選取vCenter所在的時區。



| 準備好完成 | 檢閱頁面並按一下*「Finish」（完成）*。 
|===
+

NOTE: 所有主機都必須設定IP位址（不支援FQDN主機名稱）。部署作業不會在部署之前驗證您的輸入。

. 瀏覽至SnapCenter 部署VMware vSphere的VMware vSphere的VMware vCenter外掛程式所在的VM、然後按一下* Summary（摘要）*索引標籤、再按一下* Power On*（開機）方塊以啟動SnapCenter VMware的VMware插件。
. 當VMware插件正在開機時SnapCenter 、在已部署SnapCenter 的VMware版插件上按一下滑鼠右鍵、選取* Guest OS*、然後按一下*「Install VMware tools*（安裝VMware工具*）」。
+
部署可能需要幾分鐘的時間才能完成。當啟用VMware vCenter外掛程式、安裝VMware工具、螢幕會提示您登入VMware的更新程式時、就會顯示部署成功的訊息SnapCenter 。SnapCenter

+
螢幕會顯示SnapCenter 部署VMware vCenter外掛程式的IP位址。記下IP位址。如果您想要變更VMware插件組態、則必須登入SnapCenter VMware的更新程式管理GUI SnapCenter 。

. 使用部署畫面上顯示的IP位址、使用部署精靈中提供的認證登入SnapCenter VMware更新程式管理GUI、然後在儀表板上確認SnapCenter VMware更新程式已成功連線至vCenter並已啟用。
+
請使用「https://<appliance-IP-address>:8080`」格式來存取管理GUI。

+
維護主控台使用者名稱設定為 `maint` 根據預設、您可以在安裝時設定密碼。

. 登入vCenter HTML5用戶端、然後按一下工具列中的*功能表*、然後選取* SnapCenter 適用於VMware vSpher*的「*插件」

