---
sidebar: sidebar 
permalink: scpivs44_add_a_single_vm_or_datastore_to_a_resource_group.html 
keywords:  
summary: 您可以快速將單一VM或資料存放區新增至SnapCenter 任何由VMware vSphere的VMware vSphere的VMware vCenter外掛程式管理的現有資源群組。 
---
= 將單一VM或資料存放區新增至資源群組
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以快速將單一VM或資料存放區新增至SnapCenter 任何由VMware vSphere的VMware vSphere的VMware vCenter外掛程式管理的現有資源群組。

.關於這項工作
您可以新增SAN和NAS資料存放區、但不能新增VSAN或VVOL資料存放區。

.步驟
. 在VMware vSphere用戶端GUI中、按一下工具列中的*功能表*、然後瀏覽至您要新增的VM或資料存放區。
. 在左側導覽器窗格中、以滑鼠右鍵按一下VM或資料存放區、從SnapCenter 下拉式清單中選取* NetApp Sori*、然後從次要下拉式清單中選取*「Add to Resource Group*（新增至資源群組*）」。
+
系統會先檢查SnapCenter 哪些是由元件管理、並與所選VM所在的儲存系統相容、然後顯示「*新增至資源群組*」頁面。如果SnapCenter 顯示「不兼容錯誤」訊息、表示所選的VM與SnapCenter 不兼容、您必須先將適當的儲存VM新增SnapCenter 至

. 在「*新增至資源群組*」頁面中、選取資源群組、然後按一下「*確定*」。
+
當您按一下「*確定*」時、系統會先檢查SnapCenter 哪些項目可加以管理、並與所選VM或資料存放區所在的儲存區相容。

+
如果SnapCenter 顯示訊息「民選<resource-name> is not soresible」（選擇的<resource-name>不相容）、則表示所選的VM或資料存放區與SnapCenter 該功能不相容。請參閱 link:scpivs44_create_resource_groups_for_vms_and_datastores.html#manage-compatibility-check-failures["管理相容性檢查失敗"] 以取得更多資訊。


