---
sidebar: sidebar 
permalink: scpivs44_properties_you_can_override.html 
keywords:  
summary: 您可以使用「shCBR.override」組態檔中列出的內容來變更預設值。 
---
= 您可以置換的內容
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用「shCBR.override」組態檔中列出的內容來變更預設值。

* 根據預設、範本會使用雜湊符號來註解組態內容。若要使用屬性來修改組態值、您必須移除「#」字元。
* 您必須在SnapCenter VMware vSphere主機的VMware vSphere插件上重新啟動服務、變更才會生效。


您可以使用「shCBR.override」組態檔中列出的下列內容來變更預設值。

* * dashboard.protected.vm.count.interval=7*
+
指定儀表板顯示VM保護狀態的天數。

+
預設值為「7」。

* * disable.rakCiphers=true*
+
停用下列弱式加密器、用於SnapCenter VMware vSphere和SnapCenter VMware vSphere的Rsorese-Plug-In和任何其他列於「include.runciphers'：TLS_RSA_with _AES-256_CBC_SHA256 TLS_DHE_RSA_with _AES-256_CB_SHA256_SHA256_TLs_RSA_CA_CA_CA_CAST_CA_AES的任何其他弱式加密通道、搭配AES-256_AA_CAST_CAST_CA_CA_CAST_CAST_CA_CA_256與A256_CA_CAST_CA_CA_CAST_CA_CA_CAST_256、搭配A_CAST_CA_CAST_CA_CA_CAST_CA_CAST_256、使用A_CAST_CAST_CAST_256與A_CAST_CAST_CAST_CAST_256、以A_256與A_256

* * globe.ds.site.Pattern*
+
指定一或多個要從備份作業中排除的傳統或vVol資料存放區。您可以使用任何有效的Java規則運算式來指定資料存放區。

+
範例1：「globe.ds.exclude.Pattern=.*21」這個運算式不包括具有通用模式的資料存放區、例如「datastore21」和「dest21」。

+
範例2：運算式「globe.ds.exitation.Pattern=DS-.*|^vol123」會排除所有包含「ds-」（例如「shCVDS-test」）或開頭為「vol123」的資料存放區。

* * guestFileRestore.guest.operation.interval=5*
+
指定SnapCenter VMware vSphere的VMware vSphere的VMware vCenter插件完成來賓操作所需的時間間隔（秒）（線上磁碟和還原檔案）。總等待時間由「guestFileRestore、online、disk.timeout」和「guestFileRestore、estore.file.timeout」設定。

+
預設值為「5」。

* * guestFileRestore.monitorInterval=30*
+
指定 SnapCenter Plug-in for VMware vSphere 監控已過期來賓檔案還原工作階段的時間間隔（以分鐘為單位）。在設定的工作階段時間之後執行的任何工作階段都會中斷連線。

+
預設值為「30」。

* * guestFileRestore.one.disk.timeout=100*
+
指定 SnapCenter Plug-in for VMware vSphere 等待來賓 VM 上的線上磁碟作業完成的時間（以秒為單位）。請注意、在外掛程式輪詢以完成線上磁碟作業之前、還有30秒的等待時間。

+
預設值為「100」。

* * guestFileRestore.fest.file.timeout=3600*
+
指定 SnapCenter Plug-in for VMware vSphere 等待來賓 VM 上還原檔案作業完成的時間（以秒為單位）。如果超過時間、程序就會結束、工作就會標示為失敗。

+
預設值為「3、600」（1小時）。

* * guestFileRestore.Robocopy.directory.flags=/R:0 /W:0 /ZB /CopyAll /EFSRAW /a-:SH /e /NJH /NDL /NP*
+
指定在客體檔案還原作業期間複製目錄時要使用的額外Robocopy旗標。

+
請勿移除「/NJH」或新增「/NJs」、因為這會中斷還原輸出的剖析。

+
請勿允許無限重試（移除「/R」旗標）、因為這可能會導致無法持續重試失敗的複本。

+
預設值為「/R=0 /W=0 /ZB /CopyAll /EFSRAW /A-:SH /e /NJH /NDL /Np」。

* * guestFileRestore.Robocopy.file.flags=/R:0 /W:0 /ZB /CopyAll /EFSRAW /a-:SH /NJH /NDL /NP*
+
指定在客體檔案還原作業期間複製個別檔案時要使用的額外Robocopy旗標。

+
請勿移除「/NJH」或新增「/NJs」、因為這會中斷還原輸出的剖析。

+
請勿允許無限重試（移除「/R」旗標）、因為這可能會導致無法持續重試失敗的複本。

+
預設值為「/R=0 /W=0 /ZB /CopyAll /EFSRAW /A-:SH /NJH /NDL /Np」。

* * guestFileRestore.sessionTime=1440*
+
指定SnapCenter VMware vSphere的VMware vSphere之VMware vSphere的VMware還原外掛程式保持作用中客體檔案還原工作階段的時間（以分鐘為單位）。

+
預設值為「1440」（24小時）。

* * guestFileRestore.use.custom.online.disk.script=true*
+
指定在建立客體檔案還原工作階段時、是否使用自訂指令碼來進行內嵌磁碟和擷取磁碟機代號。指令碼必須位於「[Install Path]\etc\guestFileRestore_online.ps1'。安裝時會提供預設指令碼。在附加程序期間、指令碼中會取代「[Disk_Serial_number]」、「[Online_Disk _Output」和「[Drive_Output」等值。

+
預設值為「假」。

* * include.esx.initiator.id.from.cluster=true*
+
指定 VMware vSphere 的 SnapCenter 外掛程式應在 VMDK 工作流程中、包含叢集中所有 ESXi 主機的 iSCSI 和 FCP 啟動器 ID 。

+
預設值為「假」。

* *包括.r弱 密碼*
+
當「disables.weakCiphers」設定為「true」時、除了預設停用「disables.rakCiphers」的弱密碼之外、還會指定您要停用的弱密碼。

* *最大並行.ds.storage。query.count=15*
+
指定 SnapCenter Plug-in for VMware vSphere 可撥打 SnapCenter 伺服器以探索資料存放區的儲存佔用空間的最大並行通話數。當您重新啟動 SnapCenter Plug-in for VMware vSphere VM 主機上的 Linux 服務時、外掛程式會撥打這些電話。

* * NFs.datastore.mount.retry。count=3*
+
指定 SnapCenter Plug-in for VMware vSphere 嘗試在 vCenter 中將 Volume 掛載為 NFS 資料存放區的最大次數。

+
預設值為「3」。

* * nfs.datastore.mount.retry.delay=60000*
+
指定 SnapCenter Plug-in for VMware vSphere 在 vCenter 中嘗試將磁碟區掛載為 NFS 資料存放區之間等待的時間（以毫秒為單位）。

+
預設值為「60000」（60秒）。

* * script.virtual.machine.count.variable.name = virtual_machines *
+
指定包含虛擬機器數的環境變數名稱。您必須先定義變數、才能在備份工作期間執行任何使用者定義的指令碼。

+
例如、virtual_machines = 2表示正在備份兩部虛擬機器。

* * script.virtual.machine.info.variable.name=VIRTUAL_MACHINE.%s*
+
提供環境變數名稱、其中包含備份中第n部虛擬機器的相關資訊。您必須先設定此變數、才能在備份期間執行任何使用者定義的指令碼。

+
例如、環境變數virtual_machine.2會提供備份中第二部虛擬機器的相關資訊。

* * script.virtual.machine.info.format=%s|%s|%s|%s|%s|%s*
+
提供有關虛擬機器的資訊。此資訊的格式設定於環境變數中、如下所示：「VM name| VM UUID | VM電源狀態（on | Off）| VM Snapshot拍攝（true|假）| IP位址（es）」

+
以下是您可能提供的資訊範例：

+
「virtual_machine.2=VM 1|564d6769-f07d-6e3B-68b1f3c29ba03a| powered _on|true | 10.0.4.2」

* *儲存設備.connection.timeout=600000*
+
指定SnapCenter 由儲存系統回應的時間（以毫秒為單位）。

+
預設值為「600000」（10分鐘）。

* * vmware.esx.ip.kernel.ip.map*
+
沒有預設值。您可以使用此值將 ESXi 主機 IP 位址對應至 VMkernel IP 位址。根據預設、 SnapCenter Plug-in for VMware vSphere 會使用 ESXi 主機的管理 VMkernel 介面卡 IP 位址。如果您希望 SnapCenter Plug-in for VMware vSphere 使用不同的 VMkernel 介面卡 IP 位址、則必須提供置換值。

+
在下列範例中、管理 VMkernel 介面卡 IP 位址為 10.225.10.56 ；不過、 SnapCenter Plug-in for VMware vSphere 使用指定的位址 10.225.11.57 和 10.225.11.58 。如果管理VMkernel介面卡IP位址為10.225.10.60、則外掛程式會使用位址10.225.11.61。

+
vmware.esx.ip.kernel.ip.map=10.225.10.56:10.225.11.57,10.225.11.58; 10.225.10.60：10.225.11.61

* * VMware.max.並行.snapshots=30*
+
指定 SnapCenter Plug-in for VMware vSphere 在伺服器上執行的並行 VMware 快照數量上限。

+
此數字會根據每個資料存放區進行檢查、只有在原則選取「VM一致」時才會核取。如果您執行的是損毀一致的備份、則此設定不適用。

+
預設值為「30」。

* * vmware.max.concurrent.snapshots.delete=30*
+
指定 SnapCenter Plug-in for VMware vSphere 在伺服器上執行的每個資料存放區並行 VMware Snapshot 刪除作業的最大數目。

+
此數字會根據每個資料存放區來檢查。

+
預設值為「30」。

* * VMware.query.unresolved.retry .count=10*
+
指定 SnapCenter Plug-in for VMware vSphere 因「 ... 保留 I/O 的時間限制」而重試傳送未解析磁碟區查詢的次數上限。 錯誤。

+
預設值為「10」。

* * VMware.quiesce.retry .count=0*
+
指定 SnapCenter Plug-in for VMware vSphere 因「 ... 保留 I/O 的時間限制」而重試傳送有關 VMware 快照的查詢的次數上限。 備份期間發生錯誤。

+
預設值為「0」。

* * vmware.quiesce.retry.interval=5*
+
指定 SnapCenter Plug-in for VMware vSphere 在傳送有關 VMware 快照的查詢之間等待的時間（以秒為單位）「 ... 限制 I/O 的時間限制」。 備份期間發生錯誤。

+
預設值為「5」。

* * vmware.query.unresolved.retry.delay= 60000*
+
指定 SnapCenter Plug-in for VMware vSphere 在傳送有關未解析磁碟區的查詢之間等待的時間量（以毫秒為單位）、因為「 ... 限制 I/O 的時間限制」。 錯誤。複製VMFS資料存放區時發生此錯誤。

+
預設值為「60000」（60秒）。

* * VMware.reconfig.vm.retry .count=10*
+
指定 SnapCenter Plug-in for VMware vSphere 重試傳送有關重新設定虛擬機器的查詢的最大次數、因為「 ... 限制 I/O 的時間限制」。 錯誤。

+
預設值為「10」。

* * vmware.reconfig.vm.retry.delay=30000*
+
指定 SnapCenter Plug-in for VMware vSphere 在傳送有關重新設定 VM 的查詢之間等待的最長時間（以毫秒為單位）、因為「 ... 限制 I/O 的時間限制」。 錯誤。

+
預設值為「30000」（30秒）。

* * VMware.rescable.HBA重試.count=3*
+
指定 SnapCenter Plug-in for VMware vSphere 在傳送有關重新掃描主機匯流排介面卡的查詢之間等待的時間量（以毫秒為單位）、因為「 ... 限制 I/O 的時間限制」。 錯誤。

+
預設值為「3」。

* * vmware.rescan.hba.retry.delay=30000*
+
指定 SnapCenter Plug-in for VMware vSphere 重新掃描主機匯流排介面卡的重試要求次數上限。

+
預設值為「30000」。


