---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: 您可以建立、修改及刪除備份資源群組、並在資源群組上執行備份作業。 
---
= 管理資源群組
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以建立、修改及刪除備份資源群組、並在資源群組上執行備份作業。


NOTE: 資源群組在虛擬儲存主控台（VSC）中稱為備份工作。



== 暫停和恢復資源群組上的作業

暫停資源組上的計劃操作。需要時再次啟用它們。

.步驟
. 在選擇控制閥外掛程式的左側瀏覽器窗格中，選取 * 資源群組 * ，選取資源群組，然後選取 * 暫停 * （或選取 * 恢復 * ）。
. 在確認方塊中，選擇 * 確定 * 以確認。


.完成後
在「資源群組」頁面上、暫停資源的工作狀態為「低於維護」。您可能需要捲動至表格右側、才能查看「工作狀態」欄。

恢復備份作業後、工作狀態會變更為「正式作業」。



== 修改資源群組

您可以在vCenter的資源群組中移除或新增資源、分離或附加原則、修改排程、或修改任何其他資源群組選項。

.關於這項工作
如果要修改資源群組名稱、請勿在VM、資料存放區、原則、備份或資源群組名稱中使用下列特殊字元：

%&*$#@！\/：*？“ < > - | ; ' ，以及空格。允許使用底線字元（_）。

.步驟
. 在選擇控制閥外掛程式的左導覽窗格中，選取 * 資源群組 * ，然後選取資源群組並選取 * 編輯 * 。
. 在 * 編輯資源群組 * 精靈的左側清單中，選取您要修改的類別，然後輸入變更。
+
您可以在多個類別中進行變更。您也可以在此選項中編輯次要受保護的資源。

. 選擇 * 下一步 * ，直到看到摘要頁面，然後選擇 * 完成 * 。




== 刪除資源群組

如果不需要保護資源，請刪除 vCenter 中的資源群組。刪除適用SnapCenter Plug-in for VMware vSphere之前，請刪除所有資源組。

.關於這項工作
所有資源組刪除操作均以強制刪除的方式執行。刪除資源組時，系統會從 vCenter 資源組中分離所有政策，從SnapCenter Plug-in for VMware vSphere中刪除該資源組，並刪除該資源組的所有備份和快照。


NOTE: 在SnapVault關係中，您無法刪除最後一個快照，因此您無法刪除資源組。在刪除SnapVault關係中的資源群組之前，請使用 System Manager 或ONTAP CLI 刪除該關係，然後刪除最後一個快照。

.步驟
. 在選擇控制閥外掛程式的左導覽窗格中，選取 * 資源群組 * ，然後選取資源群組並選取 * 刪除 * 。
. 在*刪除資源群組*確認對話方塊中，選擇*確定*進行確認。刪除資源組並不會刪除二級保護。如果需要，請使用系統管理員刪除二級保護。為資源組建立的一致性組不會自動刪除；您必須使用系統管理員或其他受支援的介面從ONTAP中手動刪除它們。

