---
sidebar: sidebar 
permalink: scpivs44_migration_overview.html 
keywords:  
summary:  
---
= 移轉總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
移轉命令只會移轉#fes4.0 SnapCenter 及更新版本#的中繼資料。如果您使用SnapCenter 的是舊版的不實功能、則必須先升級、才能進行移轉。

* 移轉內容包括
+
** 移轉內容
+
包含儲存系統、自訂節流和電子郵件設定的資訊、可在支援的支援範圍內、於支援組態檔、原則、資源群組、備份中繼資料和掛載中進行。SnapCenter SnapCenter（當移轉遇到預先編寫或後製指令碼時、會失敗）

** 未移轉的項目
+
為資源群組設定的指令碼前後

+
作用中客體檔案還原工作階段、客體檔案還原認證、以及Proxy VM

+
如果您在客體檔案還原工作階段處於作用中狀態時開始移轉、則會刪除工作階段、而且不會卸載附加的磁碟。您可能必須手動刪除附加磁碟。

+
"CBR.overroverr"組態檔



* 系統會暫停執行SnapCenter
+
為了確保移轉成功、移轉命令會暫停所有以SnapCenter NetApp註冊的主機。移轉程序成功完成後SnapCenter 、即可繼續執行更新。

* 移轉Cmdlet程序
+
您必須針對在 SnapCenter 註冊的 SnapCenter Plug-in for VMware vSphere 每個執行個體使用 Windows PowerShell Cmdlet `invoke-SCVOVAMigration` 。

+
Cmdlet會執行下列動作：

+
** 暫停所有排程、以避免移轉期間發生工作故障。成功移轉之後、排程會自動重新啟用。
** 移轉儲存連線和中繼資料。
** 建立移轉後備份的備份排程。
** 從SnapCenter Windows主機卸載現有的VMware vSphere版的VMware vCenter外掛程式。
+
如果 SnapCenter Plug-in for VMware vSphere 安裝在 SnapCenter Server 主機上、且已針對 SnapCenter 儲存庫設定保護、則移轉程序也會解除安裝 Windows 外掛程式套件、其中包含適用於 VMware vSphere 的 SnapCenter 外掛程式和適用於 Windows 的 SnapCenter 外掛程式、 然後重新安裝適用於 Windows 的最新版 SnapCenter 外掛程式、以支援儲存庫保護。在VMware GUI中的主機類型SnapCenter 從「vSphere」變更為「Windows」。

** 從Windows SnapCenter 效能更新伺服器移除vSphere主機和資源群組。
** 在適用於 VMware vSphere 的 Linux SnapCenter 外掛程式上啟動備份工作。
** 向 SnapCenter 註冊 SnapCenter Plug-in for VMware vSphere 主機、以支援虛擬化資料庫和檔案系統（透過 VMDK 備份的應用程式）的應用程式型備份。


* 中繼資料的儲存位置
+
應用程式型VMDK備份的中繼資料儲存在SnapCenter VMware Server儲存庫中。VM 和資料存放區備份的中繼資料會儲存在適用於 VMware vSphere MySQL 儲存庫的 SnapCenter 外掛程式中。


