---
sidebar: sidebar 
permalink: scpivs44_guest_file_restore_scenarios_you_might_encounter.html 
keywords:  
summary: 嘗試還原來賓檔案時、可能會遇到以下情況：來賓檔案還原工作階段為空白、來賓檔案還原附加磁碟作業失敗、或是來賓檔案還原工作階段中斷後、備份未分離。 
---
= 您可能會遇到的客體檔案還原案例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
嘗試還原來賓檔案時、可能會遇到下列任一種情況。



== 來賓檔案還原工作階段為空白

當您建立客體檔案還原工作階段、且該工作階段處於作用中狀態時、會重新啟動客體作業系統。發生這種情況時、來賓作業系統中的VMDK可能會保持離線狀態。因此、當您嘗試瀏覽客體檔案還原工作階段時、清單會空白。

若要修正此問題、請手動將VMDK重新連線至客體作業系統。VMDK上線時、客體檔案還原工作階段會顯示正確的內容。



== 客體檔案還原附加磁碟作業失敗

當您啟動來賓檔案還原作業時、會發生此問題、但即使 VMware 工具正在執行且來賓作業系統認證正確、附加磁碟作業仍會失敗。如果發生這種情況、會傳回下列錯誤：

「驗證來賓認證時發生錯誤、無法使用指定的認證來存取來賓系統：請確認VMware工具在系統上正常執行、使用的帳戶是Administrator帳戶、錯誤是System錯誤VIX錯誤代碼=（3016、0）。

若要修正此問題、請在來賓作業系統上重新啟動VMware Tools Windows服務、然後重試來賓檔案還原作業。



== 訪客電子郵件顯示？？？？？？檔案名稱

當您使用來賓檔案還原功能還原名稱中含有非英文字元的檔案或資料夾、且電子郵件通知顯示為「？？？？」時、就會發生此問題。 」以取得還原的檔案名稱。電子郵件附件會正確列出還原的檔案和資料夾名稱。



== 停用客體檔案還原工作階段之後、不會分離備份

當您從VM一致的備份執行客體檔案還原作業時、就會發生此問題。當客體檔案還原工作階段處於作用中狀態時、會針對同一個VM執行另一個VM一致的備份。當來賓檔案還原工作階段中斷連線時、無論是手動或24小時後自動中斷連線、工作階段的備份都不會中斷連線。

若要修正此問題、請手動將附加於作用中客體檔案還原工作階段的VMDK分離。
