---
sidebar: sidebar 
permalink: scpivs44_view_status_information.html 
keywords:  
summary: 您可以在vSphere用戶端儀表板上檢視狀態資訊。狀態資訊每小時更新一次。 
---
= 檢視狀態資訊
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在vSphere用戶端儀表板上檢視狀態資訊。狀態資訊每小時更新一次。

.步驟
. 從 vCenter 用戶端捷徑頁面、選取適用於 VMware vSphere （ SCV ）的 SnapCenter 外掛程式。
. 在選擇控制閥左側導航窗格中，選擇 *Dashboard * > *Status* 。
. 如下表所列，檢視概觀狀態資訊或選取連結以取得更多詳細資料。
+
|===
| 此儀表板方塊… | 顯示下列資訊… 


 a| 
最近的工作活動
 a| 
最新的三到五個備份、還原及掛載工作。

** 選取工作 ID 以查看該工作的詳細資料。
** 選取 * 查看全部 * 以移至「工作監控」標籤，以取得所有工作的詳細資料。




 a| 
工作
 a| 
在所選時間範圍內執行的每個工作類型（備份、還原及掛載）的計數。將游標停留在圖表的某個區段上、即可查看該類別的詳細資料。



 a| 
最新保護摘要
 a| 
所選時間範圍內主要與次要VM或資料存放區的資料保護狀態摘要。

** 選取下拉式功能表以選取 * VMS* 或 * 資料存放區 * 。
** 對於次儲存設備、請選取* SnapVault 《*》*《*》或*《SnapMirror》*。
** 將游標停留在圖表的某個區段上、即可查看該類別中的VM或資料存放區計數。在「Successful（成功）」類別中、會針對每個資源列出最新的備份。
** 您可以編輯組態檔來變更時間範圍。預設值為7天。如需詳細資訊、請 link:scpivs44_customize_your_configuration.html["自訂您的組態"]參閱。
** 內部計數器會在每個主要或次要備份之後更新。儀表板並排顯示每六小時重新整理一次。無法變更重新整理時間。附註：如果您使用鏡射保存原則、則保護摘要的計數器會顯示在SnapVault 「圖表」中、而非SnapMirror圖表中。




 a| 
組態
 a| 
由VMware vSphere的VMware vSphere的VMware vCenter外掛程式管理的每種物件類型總數SnapCenter 。



 a| 
儲存設備
 a| 
產生的快照， SnapVault 和 SnapMirror 快照總數，以及用於主要和次要快照的儲存容量。折線圖會在90天的循環期間、以每日為單位分別繪製一線和二線儲存使用量。儲存資訊每 24 小時更新一次，時間為上午 1 ： 08 。儲存節省是邏輯容量（快照節省加上儲存耗用量）與主要儲存設備實體容量的比率。長條圖說明儲存節約效益。

將游標停留在圖表上的一行上、即可查看詳細的每日結果。

|===

