---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_from_vmdks.html 
keywords:  
summary: 您可以在Windows來賓作業系統上、從VMDK還原一或多個檔案或資料夾。 
---
= 從VMDK還原來賓檔案和資料夾
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在Windows來賓作業系統上、從VMDK還原一或多個檔案或資料夾。

根據預設、附加的虛擬磁碟可在24小時內使用、然後會自動分離。您可以在精靈中選擇在還原作業完成時自動刪除工作階段、或是隨時手動刪除來賓檔案還原工作階段、或是在「*來賓組態*」頁面中延長時間。

客體檔案或資料夾還原效能取決於兩個因素：要還原的檔案或資料夾大小、以及要還原的檔案或資料夾數目。如果要還原的資料集大小相同、與還原少量大型檔案相比、還原大量的小型檔案可能需要比預期更長的時間。


IMPORTANT: 在VM上同時只能執行一個附加或還原作業。您無法在同一個VM上執行平行附加或還原作業。


IMPORTANT: 來賓還原功能可讓您檢視及還原系統和隱藏檔案、以及檢視加密檔案。請勿嘗試覆寫現有的系統檔案、或將加密的檔案還原至加密的資料夾。還原作業期間、來賓檔案的隱藏、系統和加密屬性不會保留在還原的檔案中。檢視或瀏覽保留的分割區可能會導致錯誤。

.步驟
. 按一下「*功能表*」並選取「*主機與叢集*」功能表選項、然後選取虛擬機器、再選取「* NetApp SnapCenter 還原*」、然後按一下「*客體檔案還原*」。
. 在VMware vSphere Web用戶端中、按一下次要下拉式清單中的*來賓檔案還原*、即可啟動精靈。
. 在「*還原範圍*」頁面上、執行下列動作、指定包含您要附加之虛擬磁碟的備份：
+
.. 在*備份名稱*表格中、選取包含您要附加之虛擬磁碟的備份。
.. 在「* VMDDK *」表格中、選取包含您要還原之檔案或資料夾的虛擬磁碟。
.. 在*位置*表格中、選取您要附加的虛擬磁碟位置（主要或次要）。


. 在*訪客詳細資料*頁面上、執行下列動作。
+
.. 選擇要連接虛擬磁碟的位置：
+
|===
| 選取此選項… | 如果… 


| 使用來賓VM  a| 
您想要將虛擬磁碟附加至啟動精靈之前按一下滑鼠右鍵的VM、然後選取您按一下滑鼠右鍵的VM認證。


NOTE: 必須已為虛擬機器建立認證。



| 使用客體檔案還原Proxy VM  a| 
您想要將虛擬磁碟附加至Proxy VM、然後選取Proxy VM。


NOTE: 必須先設定Proxy VM、才能開始附加與還原作業。

|===
.. 選取*傳送電子郵件通知*選項。
+
如果您想要在附加作業完成時收到通知、而且虛擬磁碟可用、則必須使用此選項。通知電子郵件包含虛擬磁碟名稱、VM名稱、以及新指派給VMDK的磁碟機代號。

+

TIP: 啟用此選項、因為客體檔案還原是非同步作業、而且可能會有時間延遲、無法為您建立來賓工作階段。

+
此選項會使用在vCenter中設定VMware vSphere Web用戶端時所設定的電子郵件設定。



. 檢閱摘要、然後按一下「*完成*」。
+
按一下「*完成*」之前、您可以返回精靈中的任何頁面並變更資訊。

. 等待附加作業完成。
+
您可以在儀表板工作監控器中檢視作業進度、也可以等待電子郵件通知。

. 若要尋找您要從附加虛擬磁碟還原的檔案、請按一下*功能表> SnapCenter VMware vSphere*的「更新外掛程式」、然後在左導覽窗格中按一下*「來賓檔案還原」*、然後選取「*來賓組態*」索引標籤。
+
在「Guest工作階段監視器」表格中、您可以按一下「*」來顯示工作階段的其他資訊。 *在右欄。

. 選取通知電子郵件中所列虛擬磁碟的客體檔案還原工作階段。
+
所有分割區都會指派磁碟機代號、包括系統保留的分割區。如果VMDK有多個分割區、您可以在「來賓檔案瀏覽」頁面頂端磁碟機欄位的下拉式清單中選取磁碟機、以選取特定磁碟機。

. 按一下*瀏覽檔案*圖示、即可檢視虛擬磁碟上的檔案與資料夾清單。
+
當您按兩下資料夾以瀏覽並選取個別檔案時、擷取檔案清單時可能會有時間延遲、因為擷取作業是在執行時間執行。

+
若要更輕鬆地瀏覽、您可以在搜尋字串中使用篩選條件。篩選器是區分大小寫的Perl運算式、不含空格。預設的搜尋字串是「.`*」。下表顯示一些Perl搜尋運算式範例。

+
|===
| 此表達式… | 搜尋… 


| 。 | 除換行字元以外的任何字元。 


| .* | 任何字串。這是預設值。 


| 答 | 字元.. 


| AB | 字串ab. 


| a [垂直列] b | 字元A或b. 


| 答* | 字元a的執行個體數為零或多個 


| A+ | 字元的一或多個執行個體.. 


| 答？ | 字元a的零或一個執行個體.. 


| a｛x｝ | 字元a的執行個體數目恰好為x 


| a｛x、｝ | 至少x個字元的執行個體數a. 


| a｛x、y｝ | 至少x個字元A的執行個體數、最多y個。 


| \ | 轉義特殊字元。 
|===
+
「來賓檔案瀏覽」頁面會顯示所有隱藏的檔案和資料夾、以及所有其他檔案和資料夾。

. 選取您要還原的一或多個檔案或資料夾、然後按一下*選取還原位置*。
+
要還原的檔案和資料夾會列在「選取的檔案」表格中。

. 在「*選取還原位置*」頁面中、指定下列項目：
+
|===
| 選項 | 說明 


| 還原至路徑 | 輸入要還原所選檔案之客體的UNC共用路徑。例如：「\10.6.0.136.65\c$' IPv6範例：「\fd20-8b1e-b255-832e--61.ipv6-literal.net\C\restore`」 


| 如果原始檔案存在  a| 
如果要還原的檔案或資料夾已存在於還原目的地、請選取要採取的動作：「永遠覆寫」或「永遠跳過」。


NOTE: 如果資料夾已經存在、則資料夾的內容會與現有資料夾合併。



| 成功還原後中斷來賓工作階段連線 | 如果希望在還原作業完成時刪除客體檔案還原工作階段、請選取此選項。 
|===
. 按一下 * 還原 * 。
+
您可以在儀表板工作監控器中檢視還原作業的進度、也可以等待電子郵件通知。傳送電子郵件通知所需的時間取決於還原作業完成所需的時間長度。

+
通知電子郵件包含附件、其中包含還原作業的輸出。如果還原作業失敗、請開啟附件以取得其他資訊。


