---
sidebar: sidebar 
permalink: scpivs44_remove_plugin.html 
keywords:  
summary: 如果您不再需要使用 SnapCenter 資料保護功能、則必須停用 SnapCenter Plug-in for VMware vSphere 、將其從 vCenter 解除登錄、然後從 vCenter 移除 SnapCenter Plug-in for VMware vSphere 、然後手動刪除剩餘檔案。 
---
= 移除SnapCenter VMware vSphere的功能性外掛程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您不再需要使用 SnapCenter 資料保護功能、則必須停用 SnapCenter Plug-in for VMware vSphere 、將其從 vCenter 解除登錄、然後從 vCenter 移除 SnapCenter Plug-in for VMware vSphere 、然後手動刪除剩餘檔案。

.開始之前
* 您必須擁有系統管理員權限。
* 請確定沒有SnapCenter 執行任何不可用的功能。


.步驟
. 使用以下格式登入SnapCenter Plug-in for VMware vSphere管理使用者介面 `\https://<OVA-IP-address>:8080`。
+
部署外掛程式時、會顯示 SnapCenter Plug-in for VMware vSphere 的 IP 位址。

. 在左側導航窗格中選擇 *Configuration* ，然後取消選擇 *Plug-In Details* 部分中的 Service 選項以禁用插件。
. 登入VMware vSphere。
. 在左側導覽器畫面中、以滑鼠右鍵按一下 SnapCenter Plug-in for VMware vSphere 執行個體（部署虛擬應用裝置時所使用的檔案名稱 `.tar` ）、然後選取 * 從磁碟刪除 * 。
. 如果您使用適用於 VMware vSphere 的 SnapCenter 外掛程式來支援其他 SnapCenter 外掛程式以進行應用程式一致的備份、請登入 SnapCenter 並移除 vSphere 主機。


.完成後
虛擬應用裝置仍在部署中、但已移除適用於 VMware vSphere 的 SnapCenter 外掛程式。

移除 SnapCenter Plug-in for VMware vSphere 的主機 VM 之後、外掛程式可能會一直列在 vCenter 中、直到本機 vCenter 快取重新整理為止。但是、由於外掛程式已移除、因此無法SnapCenter 在該主機上執行任何VMware vSphere功能。如果您想要重新整理本機 vCenter 快取、請先確定裝置在 SnapCenter Plug-in for VMware vSphere Configuration 頁面上處於「已停用」狀態、然後重新啟動 vCenter Web 用戶端服務。
