---
sidebar: sidebar 
permalink: scpivs44_mount_a_backup.html 
keywords:  
summary: 若要存取備份中的檔案、您可以從備份掛載傳統資料存放區。您可以將備份掛載到建立備份的同一個ESXi主機、或掛載到具有相同類型VM和主機組態的替代ESXi主機。您可以在主機上多次掛載資料存放區。 
---
= 掛載備份
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要存取備份中的檔案、您可以從備份掛載傳統資料存放區。您可以將備份掛載到建立備份的同一個ESXi主機、或掛載到具有相同類型VM和主機組態的替代ESXi主機。您可以在主機上多次掛載資料存放區。

您無法掛載vVol資料存放區。

.開始之前
* 確保備用ESXi主機可連線至儲存設備
+
如果您要掛載到替代的ESXi主機、您必須確定替代的ESXi主機可以連線至儲存設備、並具有下列項目： 與原始主機相同的UID和GID *。*與SnapCenter 原始主機相同的VMware vSphere版本適用於VMware vSphere的虛擬應用裝置

* 將儲存啟動器對應至ESXi
+
確保儲存系統的啟動器已對應至ESXi。

* 清除過時的LUN
+
由於ESXi每個資料存放區只能探索一個唯一的LUN、因此如果找到多個LUN、作業將會失敗。如果您在先前的掛載作業完成之前啟動掛載作業、或是手動複製LUN、或是在卸載作業期間未從儲存設備刪除複本、就會發生這種情況。為了避免發現多個複本、您應該清除儲存設備上所有的過時LUN。



.關於這項工作
如果FabricPool 無法使用資料存放區所在的資料中心儲存層、則掛載作業可能會失敗。

.步驟
. 在VMware vSphere用戶端中、按一下工具列中的*功能表*、然後從下拉式清單中選取*儲存設備*。
. 在資料存放區上按一下滑鼠右鍵、然後在下SnapCenter 拉式清單中選取* NetApp S還原*、然後在次要下拉式清單中選取* Mount Backup *。
. 在「*掛載資料存放區*」頁面上、選取備份和備份位置（主要或次要）、然後按一下「*完成*」。
. 選用：若要驗證資料存放區是否已掛載、請執行下列步驟：
+
.. 按一下工具列中的「*功能表*」、然後從下拉式清單中選取「*儲存設備*」。
.. 左導覽器窗格會顯示您在清單頂端掛載的資料存放區。
+
如果您在SnapVault 受到SnapVault 還原排程保護且執行ONTAP 版本為8.3的目的地磁碟區上執行附加或掛載作業、您可能會在附加或掛載對話方塊畫面中看到額外的Snapshot複本。這是因為附加或掛載作業會複製SnapVault 到目的地實體磁碟區ONTAP 、並透過建立新的Snapshot複本來更新磁碟區。

+
若要防止在複製磁碟區時建立新的Snapshot複本、請關閉ONTAP 針對該磁碟區的更新排程。SnapVault先前存在的Snapshot複本不會刪除。




