---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_overview.html 
keywords:  
summary: 您可以從Windows來賓作業系統上的虛擬機器磁碟（VMDK）還原檔案或資料夾。 
---
= 工作流程、先決條件及限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以從Windows來賓作業系統上的虛擬機器磁碟（VMDK）還原檔案或資料夾。



== 來賓還原工作流程

來賓作業系統還原作業包括下列步驟：

. 附加
+
將虛擬磁碟附加至客體VM或Proxy VM、然後啟動客體檔案還原工作階段。

. 請稍候
+
請等待附加作業完成、然後再瀏覽及還原。連接時

+
作業完成後、系統會自動建立來賓檔案還原工作階段、並發出電子郵件通知

+
已傳送。

. 選取檔案或資料夾
+
在來賓檔案還原工作階段中瀏覽VMDK、然後選取一或多個要還原的檔案或資料夾。

. 還原
+
將選取的檔案或資料夾還原至指定位置。





== 還原來賓檔案和資料夾的必要條件

在Windows來賓作業系統上從VMDK還原一或多個檔案或資料夾之前、您必須瞭解所有需求。

* 必須安裝並執行VMware工具。
+
使用VMware工具提供的資訊建立與VMware來賓作業系統的連線SnapCenter 。

* Windows來賓作業系統必須執行Windows Server 2008 R2或更新版本。
+
如需支援版本的最新資訊、請 https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp互通性對照表工具IMT （不含）"^]參閱。

* 目標VM的認證資料必須指定內建的網域系統管理員帳戶或內建的本機系統管理員帳戶。使用者名稱必須是「Administrator」（管理員）。 在開始還原作業之前、您必須為要附加虛擬磁碟的VM設定認證。附加作業和後續還原作業都需要認證資料。工作群組使用者可以使用內建的本機系統管理員帳戶。
+

IMPORTANT: 如果您必須使用非內建系統管理員帳戶、但在VM內具有系統管理權限的帳戶、則必須停用客體VM上的UAC.

* 您必須知道要從還原的備份快照和 VMDK 。
+
VMware vSphere的支援還原外掛程式不支援搜尋要還原的檔案或資料夾。SnapCenter因此，在開始之前，您必須知道快照和對應 VMDK 的檔案或資料夾位置。

* 要附加的虛擬磁碟必須位於SnapCenter 不可靠的備份中。
+
包含您要還原之檔案或資料夾的虛擬磁碟必須位於VM備份中、此備份是使用VMware SnapCenter vSphere的虛擬應用裝置進行的。

* 若要使用Proxy VM、必須設定Proxy VM。
+
如果您想要將虛擬磁碟附加至Proxy VM、則必須先設定Proxy VM、才能開始附加與還原作業。

* 對於非英文字母名稱的檔案、您必須將其還原至目錄、而非單一檔案。
+
您可以還原檔案所在的目錄、還原非字母名稱的檔案、例如日文日文日文日文日文日文日文日文日文日文日文日文日文日文日文日文日文日文日文日文日文日文日文日文日文。

* 不支援從Linux客體作業系統還原
+
您無法從執行Linux客體作業系統的VM還原檔案和資料夾。不過、您可以附加VMDK、然後手動還原檔案和資料夾。如需支援來賓作業系統的最新資訊、請 https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp互通性對照表工具IMT （不含）"^]參閱。





== 客體檔案還原限制

在從客體作業系統還原檔案或資料夾之前、您應該瞭解此功能不支援的項目。

* 您無法在客體作業系統內還原動態磁碟類型。
* 如果還原加密的檔案或資料夾、加密屬性將不會保留。您無法將檔案或資料夾還原至加密的資料夾。
* 「來賓檔案瀏覽」頁面會顯示您無法篩選的隱藏檔案和資料夾。
* 您無法從Linux客體作業系統還原。
+
您無法從執行Linux客體作業系統的VM還原檔案和資料夾。不過、您可以附加VMDK、然後手動還原檔案和資料夾。如需支援來賓作業系統的最新資訊、請 https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp互通性對照表工具IMT （不含）"^]參閱。

* 您無法從NTFS檔案系統還原為FAT檔案系統。
+
當您嘗試從NTFS格式還原為FAT-format時、不會複製NTFS安全性描述元、因為該檔案系統不支援Windows安全性屬性。

* 您無法從複製的VMDK或未初始化的VMDK還原來賓檔案。
* 如果備份是在執行ONTAP VMware 9.2或更新版本的系統上執行、而且VMware一致性選項已開啟、則無法從次要備份還原。
* 您無法還原檔案的目錄結構。
+
如果選取要還原巢狀目錄中的檔案、則不會使用相同的目錄結構來還原檔案。目錄樹狀結構不會還原、只會還原檔案。如果您想要還原目錄樹狀結構、可以複製結構頂端的目錄本身。

* 您無法將來賓檔案從vVol VM還原至替代主機。
* 您無法還原加密的來賓檔案。

