---
sidebar: sidebar 
permalink: scpivs44_overview_of_different_snapcenter_guis.html 
keywords:  
summary: VMware vSphere的VMware vCenter外掛程式是獨立外掛程式、與其他的VMware vSphere外掛程式不同。SnapCenter SnapCenter您必須在vCenter中使用VMware vSphere Web用戶端GUI、才能執行VM、VMDK及資料存放區的所有備份與還原作業。 
---
= 不同SnapCenter 的圖形介面總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在您的需求環境中、您必須使用適當的GUI來執行資料保護和管理作業。SnapCenter

VMware vSphere的VMware vCenter外掛程式是獨立外掛程式、與其他的VMware vSphere外掛程式不同。SnapCenter SnapCenter您必須在vCenter中使用VMware vSphere Web用戶端GUI、才能執行VM、VMDK及資料存放區的所有備份與還原作業。您也可以使用Web用戶端GUI儀表板來監控受保護和未受保護的VM清單。對於所有其他SnapCenter 的不支援程式外掛程式（應用程式型外掛程式）、您可以使用SnapCenter 支援還原的圖形使用者介面進行備份與還原作業及工作監控。

VMware支援HTML5 vSphere Web用戶端。SnapCenter不支援vCenter Flex或複雜用戶端。

若要保護VM和資料存放區、請使用VMware vSphere Web用戶端介面。Web用戶端GUI與儲存系統上的NetApp Snapshot複製技術整合。這可讓您在數秒內備份VM和資料存放區、並還原VM、而無需讓ESXi主機離線。

此外、SnapCenter 也有一個管理GUI可在VMware插件上執行管理作業。

下表顯示各個SnapCenter 方面的GUI所執行的作業。

|===
| 使用此GUI… | 若要執行這些作業... | 若要存取這些備份... 


| vSphere Web用戶端GUI SnapCenter | VM和資料存放區備份VMDK附加及卸除資料存放區掛載、以及卸載VM和VMDK還原來賓檔案和資料夾還原 | 使用VMware vSphere Web用戶端GUI執行的VM和資料存放區備份。 


| 圖形使用者介面SnapCenter | 備份及還原VM上的資料庫和應用程式、包括保護Microsoft SQL Server、Microsoft Exchange和Oracle的資料庫。資料庫複製 | 使用SnapCenter 還原GUI執行備份。 


| VMware vSphere管理GUI的VMware外掛程式SnapCenter | 修改網路組態產生支援服務包修改NTP伺服器設定停用/啟用外掛程式 | 不適用 


| vCenter GUI | 新增選擇控制器角色至vCenter Active Directory使用者新增資源存取權限至使用者或群組 | 不適用 
|===
若要執行VM一致的備份與還原作業、您必須使用VMware vSphere Web用戶端GUI。雖然可以使用VMware工具執行某些作業、例如掛載或重新命名資料存放區、但這些作業不會登錄SnapCenter 在該儲存庫中、也無法辨識。

不支援資料庫和VM的單一Snapshot複本。SnapCenterVM和資料庫的備份必須獨立排程和執行、即使資料庫和VM位於同一個磁碟區、也會建立個別的Snapshot複本。應用程式型備份必須使用SnapCenter RASTGUI排程；VM一致的備份必須使用VMware vSphere Web用戶端GUI排程。
