---
sidebar: sidebar 
permalink: scpivs44_add_storage_01.html 
keywords:  
summary: 新增儲存設備可讓SnapCenter VMware vSphere的VMware vCenter的VMware vCenter外掛程式辨識及管理vCenter中的備份與還原作業。 
---
= 新增儲存設備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在備份或還原VM之前、您必須先新增儲存叢集或儲存VM。新增儲存設備可讓SnapCenter VMware vSphere的VMware vCenter的VMware vCenter外掛程式辨識及管理vCenter中的備份與還原作業。

* 要使用的GUI
+
使用VMware vSphere用戶端新增儲存設備。

* 大型LUN
+
VMware vSphere 4.5及更新版本的支援VMware vSphere 4.5外掛程式、可在支援高達128 TB的大型LUN上支援資料存放區。SnapCenter ASA對於大型LUN、SnapCenter 為了避免延遲、支援使用者只能使用完整配置的LUN。

* VMware虛擬磁碟區（vVols）
+
您必須先將 vVols 儲存系統新增至適用於 VMware vSphere 的 ONTAP 工具、然後將其新增至適用於 VMware vSphere 的 SnapCenter 外掛程式。

+
如需詳細資訊、請參閱 https://docs.netapp.com/vapp-98/index.jsp["VMware vSphere適用的工具ONTAP"^]



.開始之前
ESXi伺服器SnapCenter 、VMware vCenter外掛程式和每個vCenter必須同步至相同時間。如果您嘗試新增儲存設備、但vCenter的時間設定並未同步、則作業可能會失敗、並顯示Java憑證錯誤。

.關於這項工作
VMware vCenter外掛程式可在直接連線的儲存VM和儲存叢集中的儲存VM上執行備份與還原作業。SnapCenter


NOTE: 如果您使用SnapCenter VMware的VMware解決方案外掛程式來支援VMDK上的應用程式型備份、則必須使用SnapCenter 此支援GUI來輸入儲存驗證詳細資料、並登錄儲存系統。

* 若為連結模式的vCenter、您必須分別將儲存系統新增至每個vCenter。
* 如果您要新增 SVM 、則儲存 VM 的名稱必須解析為管理階層的生命。
+
如果您已在 SnapCenter 中新增儲存 VM 名稱的項目至 /etc/hosts_ 檔案、則必須確保這些項目也可從虛擬應用裝置中解析。如果沒有、您應該在應用裝置內的 /etc/hosts_ 檔案中新增類似的項目。

+
如果您新增名稱無法解析為管理LIF的儲存VM、則排程的備份工作將會失敗、因為外掛程式無法探索該儲存VM上的任何資料存放區或磁碟區。如果發生這種情況、請將儲存虛擬機器新增SnapCenter 至F地、並指定管理LIF、或新增包含儲存虛擬機器的叢集、然後指定叢集管理LIF。

* 儲存驗證詳細資料不會在SnapCenter 多個VMware插件執行個體之間、或在vCenter上的Windows SnapCenter VMware支援與SnapCenter VMware外掛程式之間共享。


.步驟
. 在vSphere用戶端的左側導覽器窗格中、按一下「*儲存系統*」。
. 在「儲存系統」頁面上、選取 * 新增 * 選項。
. 在「*新增儲存系統*」精靈中、輸入下表所列的基本儲存VM或叢集資訊：
+
|===
| 對於此欄位… | 執行此操作… 


| 儲存系統 | 輸入儲存叢集或儲存 VM 的 FQDN 或管理 LIF 的 IP 位址。
SnapCenter VMware 外掛程式不支援在不同叢集上使用相同名稱的多個儲存 VM 。 


| 驗證方法 | 選取「認證」或「認證」。支援兩種類型的憑證：- https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_a_CA_signed_certificate_for_storage_system_authentication_with_SCV["CA簽署的憑證"^]- https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_a_self-signed_certificate_for_storage_system_authentication_with_SCV["自我簽署的憑證"^] 


| 使用者名稱 | 當您選取「認證」作為驗證方法時、此欄位會顯示。輸入用於登入儲存 VM 或叢集的 ONTAP 使用者名稱。 


| 密碼 | 當您選取「認證」作為驗證方法時、此欄位會顯示。輸入儲存 VM 或叢集登入密碼。 


| 憑證 | 當您選取「憑證」作為驗證方法時、此欄位會顯示。瀏覽以選取憑證檔案。 


| 私密金鑰 | 當您選取「憑證」作為驗證方法時、此欄位會顯示。瀏覽以選取私密金鑰檔案。 


| 傳輸協定 | 選取儲存傳輸協定。 


| 連接埠 | 儲存系統接受的連接埠。
-443 用於 HTTPS 連線
80 代表 HTTP 連線 


| 逾時 | 輸入 SnapCenter VMware 外掛程式在逾時作業前應等待的秒數。預設值為 60 秒。 


| 偏好的IP | 如果儲存 VM 有多個管理 IP 位址、請勾選此方塊、然後輸入您要 SnapCenter VMware 外掛程式使用的 IP 位址。
*附註：*輸入IP位址時、請勿使用方括弧（[]）。 


| 事件管理系統（EMS）與AutoSupport 範圍設定 | 如果您想要傳送EMS訊息到儲存系統的系統記錄、或是想AutoSupport 要將還原訊息傳送到儲存系統以進行套用保護、完成還原作業或失敗作業、請選取適當的核取方塊。選取「*將AutoSupport 失敗的作業發送到儲存系統*」核取方塊和「*將SnapCenter 還原伺服器事件記錄到SysLog*」核取方塊、即可啟用AutoSupport 「還原通知」。 


| 將SnapCenter 伺服器事件記錄到syslog | 勾選此方塊以記錄SnapCenter VMware vCenter外掛程式的事件。 


| 將AutoSupport 故障操作的部分通知傳送至儲存系統 | 如果您想AutoSupport 要針對失敗的資料保護工作發出資訊提示、請勾選此方塊。您也必須在AutoSupport 儲存VM上啟用「支援功能」、並設定AutoSupport 「支援功能」電子郵件設定。 
|===
. 按一下「 * 新增 * 」。
+
如果您新增儲存叢集、則會自動新增該叢集中的所有儲存VM。自動新增的儲存VM（有時稱為「內含」儲存VM）會以連字號（-）取代使用者名稱顯示在叢集摘要頁面上。使用者名稱只會針對明確的儲存實體顯示。


