---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html 
keywords:  
summary: 若要在SnapCenter 虛擬化機器上使用支援VMware vSphere的功能來保護VM、資料存放區和應用程式一致的資料庫、您必須部署SnapCenter 適用於VMware vSphere的VMware外掛程式。 
---
= 部署SnapCenter VMware vSphere的VMware vCenter外掛程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要在SnapCenter 虛擬化機器上使用支援VMware vSphere的功能來保護VM、資料存放區和應用程式一致的資料庫、您必須部署SnapCenter 適用於VMware vSphere的VMware外掛程式。

.開始之前
本節列出開始部署之前應採取的所有必要行動。


NOTE:  VMware vCenter 7u1及更新版本支援OVA部署。

* 您必須閱讀部署需求。
* 您必須執行受支援版本的vCenter Server。
* 您必須已設定及設定vCenter Server環境。
* 您必須為 VMware vSphere VM 的 SnapCenter 外掛程式設定 ESXi 主機。
* 您必須已下載SnapCenter VMware vSphere .tar的VMware解決方案。
* 您必須擁有vCenter Server執行個體的登入驗證詳細資料。
* 您必須擁有具有有效公開金鑰和私密金鑰檔案的憑證。如需詳細資訊、請參閱第節中的文章 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_Certificate_Resolution_Guide["儲存憑證管理"] 。
* 您必須登出並關閉 vSphere 用戶端的所有瀏覽器工作階段、並刪除瀏覽器快取、以避免在部署 SnapCenter Plug-in for VMware vSphere 期間發生瀏覽器快取問題。
* 您必須在vCenter中啟用傳輸層安全性（TLS）。請參閱VMware文件。
* 如果您計畫在 vCenter 中執行備份、但部署 SnapCenter Plug-in for VMware vSphere 的 vCenter 除外、那麼 ESXi 伺服器、 SnapCenter Plug-in for VMware vSphere 、以及每個 vCenter 都必須同步到同一時間。
* 若要保護VVol資料存放區上的VM、您必須先部署ONTAP VMware vSphere的功能介紹工具。如需支援版本的 ONTAP 工具的最新資訊、請 https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp 互通性對照表工具"^]參閱。可在VMware Web用戶端上配置及配置VMware上的儲存設備ONTAP ONTAP 。


將 SnapCenter Plug-in for VMware vSphere 部署在與 vCenter 相同的時區。備份排程會在部署 SnapCenter Plug-in for VMware vSphere 的時區執行。 vCenter 會在 vCenter 所在的時區中報告資料。因此、如果 SnapCenter Plug-in for VMware vSphere 和 vCenter 位於不同的時區、 SnapCenter Plug-in for VMware vSphere 儀表板中的資料可能與報告中的資料不同。

.步驟
. 若為VMware vCenter 7.0.3及更新版本、請依照中的步驟進行 link:scpivs44_download_the_ova_open_virtual_appliance.html["下載開放式虛擬應用裝置（OVA）"^] 可將證書導入vCenter。
. 在瀏覽器中、瀏覽至VMware vSphere vCenter。
+

NOTE: 對於 IPv6 位址 HTML Web 用戶端，您必須使用 Chrome 或 Firefox 。

. 登入「* VMware vCenter單一登入*」頁面。
. 在導覽器窗格中、以滑鼠右鍵按一下虛擬機器的有效父物件（例如資料中心、叢集或主機）、然後選取 * 部署 OVF Template* 以啟動 VMware 部署精靈。
. 將包含.ova檔案的.tar檔案擷取至本機系統。在「*選取OVF範本*」頁面上、指定的位置 `.ova` 檔案位於.tar解壓縮資料夾內。
. 選擇*下一步*。
. 在 * 選取名稱和資料夾 * 頁面上，輸入 VM 或 vApp 的唯一名稱，然後選取部署位置，然後選取 * 下一步 * 。
+
此步驟會指定匯入的位置 `.tar` 歸檔至vCenter。VM的預設名稱與所選的名稱相同 `.ova` 檔案：如果您變更預設名稱、請在每個vCenter Server VM資料夾中選擇唯一的名稱。

+
VM的預設部署位置是啟動精靈的詳細目錄物件。

. 在 * 選取資源 * 頁面上，選取要執行已部署 VM 範本的資源，然後選取 * 下一步 * 。
. 在 * 檢閱詳細資料 * 頁面上，確認 `.tar`範本詳細資料，然後選取 * 下一步 * 。
. 在「*授權合約*」頁面上、勾選「*我接受所有授權合約*」核取方塊。
. 在「*選取儲存設備*」頁面上、定義儲存已部署OVF範本檔案的位置和方式。
+
.. 選取VMDK的磁碟格式。
.. 選取VM儲存原則。
+
只有在目的地資源上啟用儲存原則時、才能使用此選項。

.. 選取要儲存已部署OVA範本的資料存放區。
+
組態檔和虛擬磁碟檔案會儲存在資料存放區中。

+
選取足以容納虛擬機器或vApp及所有相關虛擬磁碟檔案的資料存放區。



. 在「*選取網路*」頁面上、執行下列動作：
+
.. 選取來源網路並將其對應至目的地網路、
+
來源網路欄會列出OVA範本中定義的所有網路。

.. 在 *IP Allocation Settings* 部分中，選擇所需的 IP 地址協議，然後選擇 *Next* 。
+
VMware vSphere的VMware vSphere外掛程式支援單一網路介面。SnapCenter如果您需要多個網路介面卡、則必須手動設定。請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_additional_network_adapters_in_NDB_and_SCV_4.3["KB文章：如何建立其他網路介面卡"^]。



. 在*自訂範本*頁面上、執行下列動作：
+
.. 在「*登錄至現有vCenter *」區段中、輸入虛擬應用裝置的vCenter名稱和vCenter認證。
+
在* vCenter使用者名稱*欄位中、以「domain\username'格式輸入使用者名稱。

.. 在「*建立選擇控制閥認證資料*」區段中、輸入本機認證資料。
+
在*使用者名稱*欄位中、輸入本機使用者名稱；請勿包含網域詳細資料。

+

IMPORTANT: 記下您指定的使用者名稱和密碼。如果您稍後想要修改 SnapCenter Plug-in for VMware vSphere 組態、則需要使用這些認證。

.. 輸入主要使用者的認證資料。
.. 在 * 設定網路內容 * 區段中、輸入主機名稱。
+
... 在 * 設定 IPv4 網路內容 * 區段中、輸入網路資訊、例如 IPv4 位址、 IPv4 網路遮罩、 IPv4 閘道、 IPv4 主要 DNS 、 IPv4 次要 DNS 、 和 IPv4 搜尋網域。
... 在 * 設定 IPv6 網路內容 * 區段中、輸入網路資訊、例如 IPv6 位址、 IPv6 網路遮罩、 IPv6 閘道、 IPv6 主要 DNS 、 IPv6 次要 DNS 、 和 IPv6 搜尋網域。
+
如果適用，請選取 IPv4 或 IPv6 位址欄位，或兩者都選取。如果同時使用 IPv4 和 IPv6 位址，則只需指定其中一個位址的主要 DNS 。

+

IMPORTANT: 如果您想繼續使用DHCP做為網路組態、您可以跳過這些步驟、並將「*設定網路內容*」區段中的項目保留空白。



.. 在*設定日期與時間*中、選取vCenter所在的時區。


. 在 * 準備完成 * 頁面上，檢閱該頁面，然後選取 * 完成 * 。
+
所有主機都必須設定IP位址（不支援FQDN主機名稱）。部署作業不會在部署之前驗證您的輸入。

+
您可以從「近期工作」視窗檢視部署進度、同時等待OVF匯入和部署工作完成。

+
SnapCenter Plug-in for VMware vSphere 成功部署後、即會部署為 Linux VM 、並向 vCenter 註冊、並安裝 VMware vSphere 用戶端。

. 瀏覽至部署 SnapCenter Plug-in for VMware vSphere 的虛擬機器，然後選取 * Summary （摘要） * 索引標籤，然後選取 * Power On* （開啟電源）方塊以啟動虛擬應用裝置。
. 當 SnapCenter Plug-in for VMware vSphere 開機時，以滑鼠右鍵按一下部署的 SnapCenter Plug-in for VMware vSphere ，選取 * 來賓作業系統 * ，然後選取 * 安裝 VMware 工具 * 。
+
VMware 工具安裝在部署 SnapCenter Plug-in for VMware vSphere 的 VM 上。如需安裝VMware工具的詳細資訊、請參閱VMware文件。

+
部署可能需要幾分鐘的時間才能完成。SnapCenter Plug-in for VMware vSphere 開機、 VMware 工具安裝完成、畫面會提示您登入適用於 VMware vSphere 的 SnapCenter 外掛程式、表示部署成功。您可以在第一次重新開機期間、將網路組態從DHCP切換為靜態。但是、不支援從靜態切換至DHCP。

+
畫面會顯示部署 SnapCenter Plug-in for VMware vSphere 的 IP 位址。記下IP位址。如果您想要變更 SnapCenter Plug-in for VMware vSphere 組態、則需要登入 SnapCenter Plug-in for VMware vSphere 管理 GUI 。

. 使用部署畫面上顯示的 IP 位址、以及您在部署精靈中提供的認證、登入 SnapCenter Plug-in for VMware vSphere 管理 GUI 、 然後在儀表板上確認 SnapCenter Plug-in for VMware vSphere 已成功連線至 vCenter 並已啟用。
+
使用格式 `\https://<appliance-IP-address>:8080` 存取管理GUI。

+
使用部署時設定的管理員使用者名稱和密碼、以及使用維護主控台產生的 MFA 權杖登入。

+
如果未啟用 SnapCenter Plug-in for VMware vSphere 、請參閱 link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["重新啟動VMware vSphere用戶端服務"]。

+
如果主機名稱為「UnifiedVSC/選擇控制器」、請重新啟動應用裝置。如果重新啟動應用裝置並未將主機名稱變更為指定的主機名稱、則必須重新安裝應用裝置。



.完成後
您應該完成必要的 link:scpivs44_post_deployment_required_operations_and_issues.html["部署後作業"]。
