---
sidebar: sidebar 
permalink: scpivs44_mount_a_backup.html 
keywords:  
summary: 若要存取備份中的檔案、您可以從備份掛載傳統資料存放區。您可以將備份掛載到建立備份的同一個ESXi主機、或掛載到具有相同類型VM和主機組態的替代ESXi主機。您可以在主機上多次掛載資料存放區。 
---
= 掛載備份
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要存取備份中的檔案、您可以從備份掛載傳統資料存放區。您可以將備份掛載到建立備份的同一個ESXi主機、或掛載到具有相同類型VM和主機組態的替代ESXi主機。您可以在主機上多次掛載資料存放區。

您無法掛載vVol資料存放區。

.開始之前
* 確保備用ESXi主機可連線至儲存設備
+
如果您想要掛載到替代的 ESXi 主機、則必須確保替代的 ESXi 主機可以連線到儲存設備、並且具有下列項目：

+
** 與原始主機相同的UID和GID
** SnapCenter Plug-in for VMware vSphere 版本與原始主機版本相同的虛擬應用裝置


* 使用 iSCSI 傳輸協定時、請確定儲存系統的啟動器已對應至 ESXi 主機。使用 NVMe 傳輸協定時、請新增控制器、將必要的子系統對應到 ESXi 主機。
* 清除過時的 LUN/ 命名空間
+
由於 ESXi 主機每個資料存放區只能探索一個唯一的 LUN/ 命名空間、因此如果找到多個 LUN 、作業將會失敗。如果您在先前的掛載作業完成之前啟動掛載作業、或是手動複製 LUN/ 命名空間、或是在卸載作業期間未從儲存設備刪除複本、就可能發生這種情況。為了避免發現多個複本、您應該清除儲存設備上所有過時的 LUN/ 命名空間。



.關於這項工作
如果FabricPool 無法使用資料存放區所在的資料中心儲存層、則掛載作業可能會失敗。

.步驟
. 在 VMware vSphere 用戶端捷徑頁面中、選取 * Storage* 。
. 在資料存放區上按一下滑鼠右鍵、然後選取 * 適用於 VMware vSphere 的 SnapCenter 外掛程式 * > * 掛載備份 * 。
. 在 * 裝載資料存放區 * 頁面上，選取備份和備份位置（主要或次要），然後選取 * 完成 * 。
. 選用：若要驗證資料存放區是否已掛載、請執行下列步驟：
+
.. 選取工具列中的 * 功能表 * ，然後從下拉式清單中選取 * 儲存 * 。
.. 左側導覽器窗格會顯示您掛載於清單頂端的資料存放區。
+
如果您在受 SnapVault 排程保護且執行 ONTAP 8.3 的 SnapVault 目的地磁碟區上執行附加或掛載作業，您可能會在「附加」或「掛載」對話方塊畫面中看到額外的快照。這是因為附加或裝載作業會複製 SnapVault 目的地 Volume ，而 ONTAP 則會建立新的快照來更新磁碟區。

+
若要防止在複製磁碟區時建立新的快照，請關閉 SnapVault 磁碟區的 ONTAP 排程。先前存在的快照不會刪除。




