---
sidebar: sidebar 
permalink: scpivs44_overview_of_different_snapcenter_guis.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere是一個獨立插件，與其他SnapCenter插件不同。您必須使用 vCenter 中的 VMware vSphere 用戶端使用者介面來執行 VM、VMDK 和資料儲存區的所有備份和還原作業。 
---
= 不同SnapCenter使用者介面概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在SnapCenter環境中，您必須使用適當的使用者介面來執行資料保護和管理作業。

SnapCenter Plug-in for VMware vSphere是一個獨立插件，與其他SnapCenter插件不同。您必須使用 vCenter 中的 VMware vSphere 用戶端使用者介面來執行 VM、VMDK 和資料儲存區的所有備份和還原作業。您也可以使用 Web 用戶端使用者介面儀表板來監控受保護和未受保護的虛擬機器清單。對於所有其他SnapCenter插件（基於應用程式的插件）操作（如備份和復原以及作業監控），您可以使用SnapCenter使用者介面。

為了保護虛擬機器和資料儲存區，您可以使用 VMware vSphere 用戶端介面。 Web 用戶端使用者介面與儲存系統上的NetApp快照技術整合。這使您能夠在幾秒鐘內備份虛擬機器和資料儲存區，並在不使 ESXi 主機離線的情況下還原虛擬機器。

還有一個管理使用者介面，用於SnapCenter Plug-in for VMware vSphere執行管理作業。

下表顯示了SnapCenter使用者介面執行的操作。

|===
| 使用此使用者介面... | 若要執行這些作業... | 若要存取這些備份... 


| SnapCenter vSphere 用戶端使用者介面 | VM和資料存放區備份VMDK附加及卸除資料存放區掛載、以及卸載VM和VMDK還原來賓檔案和資料夾還原 | 使用 VMware vSphere 用戶端使用者介面備份虛擬機器和資料儲存區。 


| SnapCenter使用者介面 | 備份及還原VM上的資料庫和應用程式、包括保護Microsoft SQL Server、Microsoft Exchange和Oracle的資料庫。資料庫複製 | 使用SnapCenter使用者介面執行的備份。 


| SnapCenter Plug-in for VMware vSphere | 修改網路組態產生支援服務包修改NTP伺服器設定停用/啟用外掛程式 | 不適用 


| vCenter 使用者介面 | 新增選擇控制器角色至vCenter Active Directory使用者新增資源存取權限至使用者或群組 | 不適用 
|===
對於虛擬機器一致的備份和還原作業，您必須使用 VMware vSphere 用戶端使用者介面。雖然可以使用 VMware 工具執行某些操作，例如掛載或重命名資料存儲，但這些操作不會在SnapCenter儲存庫中註冊，也不會被識別。

SnapCenter不支援資料庫和虛擬機器的單一快照。必須獨立安排和執行虛擬機器和資料庫的備份，即使資料庫和虛擬機器託管在同一磁碟區中，也會建立單獨的快照。必須使用SnapCenter使用者介面安排基於應用程式的備份；必須使用 VMware vSphere 用戶端使用者介面安排虛擬機器一致的備份。
