---
sidebar: sidebar 
permalink: scpivs44_disable_and_enable_plugin.html 
keywords:  
summary: 如果您不再需要 SnapCenter 資料保護功能、則必須變更 SnapCenter Plug-in for VMware vSphere 的組態。例如、如果您在測試環境中部署外掛程式、可能需要停用SnapCenter 該環境中的功能、並在正式作業環境中啟用這些功能。 
---
= 停用SnapCenter 並啟用VMware vSphere的功能支援功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您不再需要 SnapCenter 資料保護功能、則必須變更 SnapCenter Plug-in for VMware vSphere 的組態。例如、如果您在測試環境中部署外掛程式、可能需要停用SnapCenter 該環境中的功能、並在正式作業環境中啟用這些功能。

.開始之前
* 您必須擁有系統管理員權限。
* 請確定沒有SnapCenter 執行任何不可用的功能。


.關於這項工作
當您停用 SnapCenter Plug-in for VMware vSphere 時、所有資源群組都會暫停、而且外掛程式會在 vCenter 中取消登錄為擴充功能。

當您啟用 SnapCenter Plug-in for VMware vSphere 時、外掛程式會在 vCenter 登錄為擴充功能、所有資源群組都處於正式作業模式、且所有排程都會啟用。

.步驟
. 選用：備份適用於 VMware vSphere MySQL 儲存庫的 SnapCenter 外掛程式、以便將其還原至新的虛擬應用裝置。
+
link:scpivs44_back_up_the_snapcenter_plug-in_for_vmware_vsphere_mysql_database.html["備份SnapCenter VMware vSphere MySQL資料庫的VMware vCenter外掛程式"]。

. 使用格式登入 SnapCenter Plug-in for VMware vSphere 管理 GUI `\https://<OVA-IP-address>:8080`。使用部署時設定的管理員使用者名稱和密碼、以及使用維護主控台產生的 MFA 權杖登入。
+
部署外掛程式時、會顯示 SnapCenter Plug-in for VMware vSphere 的 IP 位址。

. 在左側導航窗格中選擇 *Configuration* ，然後取消選擇 *Plug-In Details* 部分中的 Service 選項以禁用插件。
. 確認您的選擇。
+
** 如果您只使用 SnapCenter Plug-in for VMware vSphere 來執行 VM 一致的備份
+
外掛程式已停用、不需要採取進一步行動。

** 如果您使用 SnapCenter Plug-in for VMware vSphere 來執行應用程式一致的備份
+
外掛程式已停用、需要進一步清理。

+
... 登入VMware vSphere。
... 關閉VM電源。
... 在左側導覽器畫面中、以滑鼠右鍵按一下 SnapCenter Plug-in for VMware vSphere 執行個體（部署虛擬應用裝置時所使用的檔案名稱 `.ova` ）、然後選取 * 從磁碟刪除 * 。
... 登入SnapCenter 以供使用、然後移除vSphere主機。





