---
sidebar: sidebar 
permalink: scpivs44_information_not_displayed_after_upgrading_to_a_new_patch_of_the_same_release.html 
keywords:  
summary: 將SnapCenter VMware vSphere的更新版的更新版更新為相同版本的新修補程式之後、儀表板和工作監控器可能不會顯示最近的工作或其他資訊。 
---
= 升級至同一版本的新修補程式後、不會顯示相關資訊
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
將SnapCenter VMware vSphere的更新版的更新版更新為相同版本的新修補程式之後、儀表板和工作監控器可能不會顯示最近的工作或其他資訊。

如果您要升級至同一版本的新修補程式、則必須清除SnapCenter vCenter Web Server上的VMware vSphere快取的VMware vSphere外掛程式、並在升級或登錄之前重新啟動伺服器。

如果外掛程式快取未清除、則在下列情況下、儀表板和工作監控器不會顯示最近的工作：

* VMware vSphere的VMware vSphere外掛程式是使用vCenter部署、之後再升級至同一版本的修補程式。SnapCenter
* VMware的VMware虛擬應用裝置已部署在vCenter 1中。SnapCenter之後、這款適用於 VMware vSphere 的 SnapCenter 外掛程式已註冊至新的 vCenter2 。SnapCenter Plug-in for VMware vSphere 的新執行個體是使用修補程式建立、並註冊至 vCenter1 。不過、由於 vCenter1 仍有第一個 SnapCenter Plug-in for VMware vSphere 的快取外掛程式、而沒有該修補程式、因此需要清除快取。


根據伺服器作業系統的類型、快取位於下列位置：

* vCenter Server Linux應用裝置
+
/etc/VMware/vSphere-client/vC-packages/vSphere-client-cronity/`

* Windows作業系統
+
`%PROGRAMFILES%/VMware/vSphere client/vc-packages/vsphere-client-serenity/`





== 如果您在清除快取之前已經升級、請採取因應措施

. 登入SnapCenter Plug-in for VMware vSphere管理使用者介面。
+
當您部署適用於 VMware vSphere 的 SnapCenter 外掛程式時、會顯示 IP 位址。

. 在左側導航窗格中選擇 * 組態 * ，然後在 * 外掛詳細資料 * 區段中選取服務選項，以停用外掛程式。
+
SnapCenter Plug-in for VMware vSphere 服務已停用、且擴充功能已在 vCenter 中取消註冊。

. 找到 `vsphere-client-serenity` 資料夾、然後找出 `com.netapp.scv.client-<release-number>` 資料夾並加以刪除。
+
每個版本的資料夾名稱都會變更。

. 重新啟動vCenter Server。
. 登入VMware vSphere用戶端。
. 在左側導航窗格中選擇 * 組態 * ，然後在 * 外掛詳細資料 * 區段中選取服務選項，以啟用外掛程式。
+
SnapCenter Plug-in for VMware vSphere 服務已啟用、且擴充功能已在 vCenter 中登錄。


