---
sidebar: sidebar 
permalink: scpivs44_concepts_overview.html 
keywords:  
summary: VMware vSphere的VMware vSphere外掛程式是一種獨立式虛擬應用裝置（開放式虛擬應用裝置格式）、可為VM和資料存放區提供資料保護服務、並支援以應用程式為基礎的插件資料保護服務。SnapCenter SnapCenter本文件說明如何部署及使用SnapCenter VMware vSphere的VMware vSphere適用的VMware vCenter外掛程式、並包含快速入門資訊。 
---
= 產品總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]
:revnumber: 
:revdate: and supports data protection services for SnapCenter application-based plug-ins. This document describes how to deploy and use SnapCenter Plug-in for VMware vSphere and includes quick start information.


VMware vSphere的VMware vSphere外掛程式部署為Linux型虛擬應用裝置。SnapCenter

SnapCenter Plug-in for VMware vSphere 可為您的環境新增下列功能：

* 支援VM一致且損毀一致的資料保護作業。
+
您可以使用 vCenter 中的 VMware vSphere 用戶端使用者介面執行 VMware 虛擬機器（傳統 VM 和 vVol VM）、VMDK 和資料儲存區的所有備份和還原作業。對於 vVol VM（vVol 資料儲存中的 VM），僅支援崩潰一致性備份。您也可以還原虛擬機器和 VMDK，以及還原駐留在來賓作業系統上的檔案和資料夾。

+
備份VM、VMDK和資料存放區時、外掛程式不支援RDM。VM的備份工作會忽略RDM。如果您需要備份RDM、則必須使用SnapCenter 以應用程式為基礎的外掛程式。

+
SnapCenter Plug-in for VMware vSphere 包含一個 MySQL 資料庫、其中包含適用於 VMware vSphere 中繼資料的 SnapCenter 外掛程式。為了提供VM一致且一致損毀的資料保護、您不需要安裝SnapCenter 任何故障伺服器。

* 支援應用程式一致的（透過VMDK-RDM的應用程式）資料保護作業。
+
您可以使用SnapCenter使用者介面和適當的SnapCenter應用程式外掛程式對虛擬機器上主儲存和二級儲存上的資料庫和檔案系統執行所有備份和復原作業。

+
SnapCenter 原生利用適用於 VMware vSphere 的 SnapCenter 外掛程式、在 VMDK 、原始裝置對應（ RDM ）和 NFS 資料存放區上執行所有資料保護作業。部署虛擬應用裝置之後、外掛程式會處理與vCenter的所有互動。SnapCenter Plug-in for VMware vSphere 支援所有 SnapCenter 應用程式型外掛程式。

+
SnapCenter不支援資料庫和虛擬機器的單一快照。必須獨立安排和執行虛擬機器和資料庫的備份，這會建立單獨的快照，即使資料庫和虛擬機器託管在同一磁碟區中。使用SnapCenter使用者介面安排資料庫應用程式備份；使用 VMware vSphere 用戶端使用者介面安排 VM 和資料儲存區備份。

* VM 一致快照需要 VMware 工具
+
如果未安裝和執行 VMware 工具，則檔案系統不會停止，並會建立一致當機的快照。

* 在SAN（VMFS）環境中進行還原作業時、必須使用VMware Storage VMotion
+
VMware檔案系統（VMFS）的還原工作流程採用VMware Storage VMotion功能。Storage VMotion是vSphere Standard授權的一部分、但不適用於vSphere Essentials或Essentials Plus授權。

+
NFS環境中的大多數還原作業都使用原生ONTAP 的還原功能（例如單一檔案SnapRestore 還原）、不需要VMware Storage VMotion。

* 設定 VMware vVol VM 需要 VMware vSphere 的 ONTAP 工具。
+
您可以使用ONTAP 支援功能來配置ONTAP 及配置VMware Web用戶端中vVols的儲存資源。

+
如需詳細資訊，請參閱 ONTAP Tools for VMware vSphere 文件。此外，如需 ONTAP 工具支援版本的最新資訊，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp 互通性對照表工具"^]。

* SnapCenter Plug-in for VMware vSphere 是部署在 Linux VM 中的虛擬應用裝置
+
雖然虛擬應用裝置必須安裝為 Linux VM 、但適用於 VMware vSphere 的 SnapCenter 外掛程式支援 Windows 型和 Linux 型 vCenter 。支援以應用程式為基礎的外掛程式、可在Windows和Linux虛擬化應用程式上執行資料保護作業、無需使用者介入、即可原生使用此外掛程式與vCenter進行通訊。SnapCenter SnapCenter



除了這些主要功能外，適用於 VMware vSphere 的 SnapCenter 外掛程式也支援 iSCSI ，光纖通道， FCoE ， NFS 3.0/4.1 ， VMFS 5.0/6.0 ， NVMe over FC 和 NVMe over TCP 。

如需支援版本的最新資訊、請參閱 https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp 互通性對照表工具"^] （ IMT ）。

如需 NFS 通訊協定和 ESXi 主機的相關資訊、請參閱 VMware 提供的 vSphere 儲存設備文件。

如需 SnapCenter 資料保護的相關資訊，請參閱中 SnapCenter 外掛程式的資料保護資訊 http://docs.netapp.com/us-en/snapcenter/index.html["資訊文件SnapCenter"^]。

如需有關支援的升級和移轉路徑的資訊、請參閱 link:scpivs44_release_notes.html["VMware vSphere的版次說明SnapCenter"^]。
