---
sidebar: sidebar 
permalink: scpivs44_upgrade_to_a_new_patch.html 
keywords:  
summary: 如果您要升級至同一版本的新修補程式、則必須清除SnapCenter vCenter Web Server上的VMware vSphere快取的VMware vSphere外掛程式、並在升級或登錄之前重新啟動伺服器。 
---
= 升級至SnapCenter 適用於VMware vSphere的同一版本的更新版更新版更新
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您要升級至同一版本的新修補程式、則必須清除SnapCenter vCenter Web Server上的VMware vSphere快取的VMware vSphere外掛程式、並在升級或登錄之前重新啟動伺服器。

如果外掛程式快取未清除、則在下列情況下、儀表板和工作監控器不會顯示最近的工作：

* VMware vSphere的VMware vSphere外掛程式是使用vCenter部署、之後再升級至同一版本的修補程式。SnapCenter
* VMware的VMware虛擬應用裝置已部署在vCenter 1中。SnapCenter之後、這款適用於 VMware vSphere 的 SnapCenter 外掛程式已註冊至新的 vCenter2 。SnapCenter Plug-in for VMware vSphere 的新執行個體是使用修補程式建立、並註冊至 vCenter1 。不過、由於 vCenter1 仍有第一個 SnapCenter Plug-in for VMware vSphere 的快取外掛程式、而沒有該修補程式、因此需要清除快取。




== 清除快取的步驟

. 找到 `vsphere-client-serenity` 資料夾、然後找出 `com.netapp.scv.client-<release-number>` 資料夾並加以刪除。
+
每個版本的資料夾名稱都會變更。

+
請參閱 VMware 說明文件、以瞭解作業系統的資料夾位置 `vsphere-client-serenity` 。

. 重新啟動vCenter Server。
+
接著即可升級適用於 VMware vSphere 的 SnapCenter 外掛程式。


