---
sidebar: sidebar 
permalink: scpivs44_register_snapcenter_plugin_vmware_vsphere_with_snapcenter_server.html 
keywords:  
summary: 如果您想在SnapCenter VMware vSphere中執行應用程式over VMDK工作流程（適用於虛擬化資料庫和檔案系統的應用程式型保護工作流程）、則必須在SnapCenter 使用VMware vSphere的VMware vSphere中註冊此外掛SnapCenter 程式。 
---
= 註冊SnapCenter VMware vSphere的VMware vCenter SnapCenter with VMware Server外掛程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您想在SnapCenter VMware vSphere中執行應用程式over VMDK工作流程（適用於虛擬化資料庫和檔案系統的應用程式型保護工作流程）、則必須在SnapCenter 使用VMware vSphere的VMware vSphere中註冊此外掛SnapCenter 程式。

如果SnapCenter 您是一個不完整的使用者、並且升級至SnapCenter VMware的版本為4、4.2、並將應用程式的over VMDK備份移轉至SnapCenter VMware的版本為2、則移轉命令會自動登錄外掛程式。

.開始之前
* 您必須執行SnapCenter 的是不含更新版本的伺服器。
* 您必須已部署並啟用SnapCenter VMware vSphere的VMware vCenter外掛程式。


.關於這項工作
* 您可以SnapCenter 使用VMware GUI新增「vSphere」類型的主機、以SnapCenter 使用VMware vSphere with VMware Server登錄支援VMware vSphere的插件SnapCenter 。
+
連接埠8144已預先定義、可在SnapCenter VMware vCenter插件內進行通訊。

+
您可以在SnapCenter 同一個SnapCenter VMware vSphere上登錄多個適用於VMware vSphere的VMware vCenter Plug-in執行個體、以支援VM上的應用程式型資料保護作業。您無法在SnapCenter 多SnapCenter 個VMware伺服器上登錄相同的VMware vSphere效能支援外掛程式。

* 若為連結模式的vCenter、您必須針對SnapCenter 每個vCenter登錄VMware vSphere的VMware vSphere版本。


.步驟
. 在「SorgGUI」左導覽窗格中、按一下「*主機*」SnapCenter 。
. 確認頂端已選取*託管主機*索引標籤、然後找出虛擬應用裝置主機名稱、並確認其可從SnapCenter 「支援伺服器」解析。
. 按一下「*新增*」以啟動精靈。
. 在「*新增主機*」對話方塊中、指定您要新增至SnapCenter 下列表格中所列的支援伺服器主機：
+
|===
| 對於此欄位… | 執行此操作… 


| 主機類型 | 選擇* vSpher*作為主機類型。 


| 主機名稱 | 驗證虛擬應用裝置的IP位址。 


| 認證資料 | 輸入SnapCenter 部署期間所提供之VMware插件的使用者名稱和密碼。 
|===
. 按一下*提交*。
+
成功新增VM主機時、它會顯示在「受管理的主機」索引標籤上。

. 在左側導覽窗格中、按一下 * 設定 * 、然後按一下 * 認證 * 索引標籤、然後選取 * 新增 * 以新增虛擬應用裝置的認證。
. 提供部署SnapCenter VMware vSphere的VMware vSphere的VMware vCenter外掛程式時所指定的認證資訊。
+

NOTE: 您必須在「驗證」欄位中選取「Linux」。



.完成後
如果SnapCenter 修改VMware vSphere的「VMware vSphere的更新外掛程式」認證、您必須SnapCenter 使用SnapCenter 「受管理的主機」頁面來更新「VMware Server」中的登錄。
