---
sidebar: sidebar 
permalink: scpivs44_restore_deleted_vms_from_backups.html 
keywords:  
summary: 您可以將刪除的VM從資料存放區的主要或次要備份還原至所選的ESXi主機。 
---
= 從備份還原刪除的VM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以將刪除的VM從資料存放區的主要或次要備份還原至所選的ESXi主機。

您可以將VM還原至下列位置：

* 還原至原始位置
+
** 安裝在原始ESXi主機上的原始資料存放區（這會製作VM複本）


* 還原至替代位置
+
** 安裝在原始ESXi主機上的不同資料存放區
** 安裝在不同ESXi主機上、由同一個vCenter管理的原始資料存放區
** 安裝在不同ESXi主機上、由同一個vCenter管理的不同資料存放區
** 安裝在不同ESXi主機上的不同資料存放區、由不同vCenter以連結模式管理





NOTE: 還原至不同位置時、SnapCenter VMware vSphere的VMware vSphere VMware Plug-in必須在連結的vCenter中執行、該vCenter是還原作業的目的地。目的地資料存放區必須有足夠的空間。


NOTE: 您無法將vVol VM還原至其他位置。


NOTE: 還原刪除的VM時、所有原先指派給VM的標記或資料夾都不會還原。

.開始之前
* 儲存系統的使用者帳戶（在VMware vSphere用戶端的「Storage Systems」（儲存系統）頁面上）必須具有 link:scpivs44_minimum_ontap_privileges_required.html["要求最低的不必要權限才能執行此功能ONTAP ONTAP"]。
* vCenter中的使用者帳戶必須具有 link:scpivs44_minimum_vcenter_privileges_required.html["適用於VMware vSphere的VMware vSphere的VMware vCenter外掛程式所需的最低權限SnapCenter"]。
* 備份必須存在。
+
您必須先使用SnapCenter VMware vSphere的VMware vSphere的VMware vCenter外掛程式建立VM備份、然後才能還原該VM上的VMDK。




TIP: 若要改善NFS環境中的還原作業效能、請啟用VMware應用程式vStorage API for Array Integration（VAAI）。

.關於這項工作
您無法還原資料存放區、但可以還原資料存放區中的任何VM。

如果FabricPool 無法使用虛擬機器所在的儲存層、還原作業可能會失敗。

.步驟
. 按一下「*功能表*」並選取「*儲存設備*」功能表選項、然後選取資料存放區、再選取「*組態*」索引標籤、然後按一下「* SnapCenter VMware vSphere的*還原外掛程式*」區段中的「*備份*」。
. 按兩下備份、即可查看備份中包含的所有VM清單。
. 從備份清單中選取刪除的VM、然後按一下*還原*。
. 在*還原*精靈的*選取備份*頁面上、選取您要還原的備份複本。
+
您可以搜尋特定的備份名稱或部分備份名稱，或是按一下篩選器圖示並選取日期和時間範圍，選取是否要包含 VMware 快照的備份，是否要掛載備份，以及位置，以篩選備份清單。按一下「*確定*」以返回精靈。

. 在 * 選取範圍 * 頁面上、在 * 還原範圍 * 欄位中選取 * 整個虛擬機器 * 、然後選取還原位置、然後輸入要掛載備份的目的地 ESXi 主機資訊。
+
還原目的地可以是任何已新增至SnapCenter VMware的ESXi主機。此選項會還原虛擬機器所在的選定備份內容，並以指定的時間和日期，從快照中還原該備份內容。如果您選取此選項並開啟VM電源、則會勾選*重新啟動VM*核取方塊。

+
如果您要將NFS資料存放區中的VM還原到ESXi叢集中的其他ESXi主機、則在還原VM之後、它會登錄到替代主機上。

. 在*選取位置*頁面上、選取您要從其中還原的備份位置（主要或次要）。
. 檢閱「摘要」頁面、然後按一下「*完成*」。

