---
sidebar: sidebar 
permalink: scpivs44_restore_vmdks_from_backups.html 
keywords:  
summary: 您可以從傳統VM或VVol VM的主要或次要備份還原現有的VMDK、或是刪除或分離的VMDK。 
---
= 從備份還原VMDK
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以從傳統VM或VVol VM的主要或次要備份還原現有的VMDK、或是刪除或分離的VMDK。

您可以將虛擬機器上的一或多個虛擬機器磁碟（VMDK）還原至相同的資料存放區。


TIP: 若要改善NFS環境中的還原作業效能、請啟用VMware應用程式vStorage API for Array Integration（VAAI）。

.開始之前
* 備份必須存在。
+
您必須使用SnapCenter VMware vSphere的VMware vSphere的VMware vCenter外掛程式來建立VM備份。

* VM不得在傳輸中。
+
您要還原的VM不得處於VMotion或Storage VMotion狀態。



.關於這項工作
* 如果VMDK已從VM刪除或分離、則還原作業會將VMDK附加至VM。
* 如果FabricPool 無法使用虛擬機器所在的儲存層、還原作業可能會失敗。
* 連接與還原作業會使用預設的SCSI控制器來連接VMDK。不過、當備份連接至具有 NVMe 磁碟的 VM 的 VMDK 時、附加和還原作業會使用 NVMe 控制器（如果有）。


.步驟
. 在 VMware vSphere 用戶端使用者介面中，選擇工具列中的“*選單*”，然後從下拉清單中選擇“*虛擬機器和範本*”。
. 在左側瀏覽器窗格中、以滑鼠右鍵按一下 VM 、然後在下拉式清單中選取 * SnapCenter Plug-in for VMware vSphere * 、然後在次要下拉式清單中選取 * 還原 * 。
. 在*還原*精靈的「選取備份」頁面上、選取您要還原的備份複本。
+
您可以搜尋特定的備份名稱或部分備份名稱，或是選取篩選器圖示並選取日期和時間範圍，選取是否要包含 VMware 快照的備份，是否要掛載備份，以及主要或次要位置，以篩選備份清單。選取 * 確定 * 以返回精靈。

. 在「*選取範圍*」頁面上、選取還原目的地。
+
|===
| 若要還原至… | 指定還原目的地… 


| 原始資料存放區 | 從下拉式清單中選取 * 特定磁碟 * ，然後選取 * 下一步 * 。在資料存放區選擇表中、您可以選取或取消選取任何VMDK。 


| 替代位置的替代資料存放區 | 選取目的地資料存放區，然後從清單中選取不同的資料存放區。 
|===
. 在 * 選取位置 * 頁面上，選取您要還原的快照（主要或次要）。
. 檢閱「摘要」頁面，然後選取 * 「完成」 * 。
. 選用：選取畫面底部的 * 最近工作 * 來監控作業進度。
. 重新整理畫面以顯示更新的資訊。

